### PR TITLE
fix(deleteBoard): board is not deleted from db on DELETE

### LINKED ISSUE #68: fix(deleteBoard): board should not be deleted from DB
**If board is deleted by user ( admin ):**

**current behavior:**
the board is removed from DB. 

**desired behavior:**
the board should save a "deleted:true" property and should not be shown client side.
board should remain in database.

### PR DESCRIPTION
**Pull request by ShragaUser**
board is flaged as isDeleted: true
deleted boards aren't sent to initialState
deleted board is persistant in DB.

closes #68

### CODE REVIEW

File: src/server/routes/api.js [hunk 1]
```diff
@@ -94,25 +94,26 @@ const api = db => {
...
       res.status(200).send();
     });
   });
 
   router.delete("/board", (req, res) => {
     const { boardId } = req.body;
-    boards.deleteOne({ _id: boardId }).then(result => {
-      res.send(result);
-    });
+    // boards.deleteOne({ _id: boardId }).then(result => {
```
Comment (ghost) [inline src/server/routes/api.js:113]: delete comments
